name: Automated Performance Testing

on:
  push:
    branches: [main]
  pull_request:

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure results folder exists 
        run: mkdir -p results

      - name: Clean results folder
        run: rm -rf ./results/*

      - name: Run JMeter tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/test-plans:/test-plans \
            -v ${{ github.workspace }}/results:/results \
            -v ${{ github.workspace }}/config:/config \
            liukunup/jmeter:5.6.3 \
            jmeter -n -t /test-plans/api-performance.jmx \
            -p /config/test.properties \
            -l /results/results.jtl \
            -e -o /results/html-report

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y bc

      - name: Check performance thresholds
        run: |
          chmod +x ./config/check-thresholds.sh
          ./config/check-thresholds.sh results/results.jtl

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-report
          path: results/
          retention-days: 30
